<?xml version="1.0"?>
<robot name="summit_xl" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

	<xacro:include filename="$(find summit_xl_description)/urdf/bases/summit_x_base.gazebo.xacro" />
  
  <macro name="box_inertia" params="m x y z">
		<inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
			iyy="${m*(x*x+z*z)/12}" iyz = "0"
			izz="${m*(x*x+z*z)/12}"
		/>
	</macro>
  
	<xacro:macro name="summit_x_base" params="name publish_bf">

	<!-- Robot mechanical and motor parameters -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="wheel_width" value="0.175" />

	<!-- BASE FOOTPRINT -->
	<xacro:if value="${publish_bf}">
		<link name="base_footprint">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</visual>
		</link>

		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${2*wheel_radius}" rpy="0 0 0" /> <!-- ${wheel_radius} property must be defined inside wheel description -->
			<parent link="base_footprint"/>
			<child link="base_link" />
		</joint>    
  </xacro:if>


  <!-- BASE_LINK -->
	<link name="base_link">
		<inertial>
			<mass value="25.0" />
			<origin xyz="0 0 0" />
			<inertia  ixx="1.391" ixy="0.004"  ixz="0.0"  iyy="6.853"  iyz="0.0"  izz="6.125" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://summit_xl_description/meshes/x_wam/chassis_xwam_down.stl"/>
			</geometry>
			<material name="summit_x_base_color">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
				<geometry>
					<mesh filename="package://summit_xl_description/meshes/x_wam/chassis_xwam_down.stl"/>
				</geometry>
		</collision>     
	</link>
	
	<!-- ***************************** --> 
  <!-- ROVER PART - UP SCISSOR MECH  --> 
  <!-- ***************************** --> 
	<link name="rover_link">
		<inertial>
			<mass value="1.0" /> <!-- 20.0 -->
			<origin xyz="0 0 0" />
			<inertia  ixx="0.2185" ixy="0.0"  ixz="-0.001"  iyy="0.33677"  iyz="0.0"  izz="0.20511" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://summit_xl_description/meshes/x_wam/chassis_xwam_up.stl"/>
			</geometry>
			<material name="summit_x_rover_color">
				<color rgba="0.1 0.1 0.1 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
			<geometry>
				<mesh filename="package://summit_xl_description/meshes/x_wam/chassis_xwam_up.stl"/>
			</geometry>
		</collision>     
	</link>

  <joint name="scissor_prismatic_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="rover_link"/>
    <limit effort="100000.0" velocity="1000.0" lower="0.0" upper="0.5"/> <!-- lower="0.1" upper="0.5" -->
    <origin rpy="0 0 0" xyz="0.261 0 -0.038"/>
    <axis xyz="0 0 1"/>
  </joint>

  <transmission name="joint_scissor_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="scissor_prismatic_joint" />
     <actuator name="scissor_motor">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
	 </actuator>
  </transmission>

  
  
  <!-- ***************************** --> 
  <!-- SCISSOR MECHANISM PART 1      --> 
  <!-- ***************************** -->
  
<!--
  <joint name="scissor_bars1_joint" type="continuous">
    <parent link="rover_link"/>
    <child link="scissor_bars1_link"/>
    <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
    <limit effort="300" velocity="10.0" lower="-20.2" upper="20.7" />
    <mimic joint="scissor_prismatic_joint" multiplier="5" offset="0.0" /> 
    <axis xyz="0 1 0" />
  </joint>
  
	<link name="scissor_bars1_link">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 -3.1415 0"/>
			<box_inertia m="1" x="0.5" y="0.2" z="0.05"/>
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 -3.1415 0" />
       <geometry>
					<mesh filename="package://summit_xl_description/meshes/x_wam/scissor_bars_1.stl"/>
					<box x="0.2" y="0.1" z="0.1"/>
       </geometry>
    </visual>
    <collision>
       <origin xyz="0 0 0" rpy="0 -3.1415 0" />
       <geometry>
				<mesh filename="package://summit_xl_description/meshes/x_wam/scissor_bars_1.stl"/>
				<box x="0.2" y="0.1" z="0.1"/>
       </geometry>
    </collision>     
  </link>
-->

	</xacro:macro>
</robot>

