summit_xl:
  joint_blw_velocity_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_brw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_frw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_flw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_front_pan
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
  joint_front_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_front_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_rear_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_rear_pan
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
  joint_rear_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_rear_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_ptu1_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: ptu1_joint_1
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_ptu1_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: ptu1_joint_2
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_ptu2_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: ptu2_joint_1
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_ptu2_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: ptu2_joint_2
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_rear_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_rear_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

  ptu_controller:
    type: position_controllers/JointTrajectoryController
    joints:
     - ptu1_joint_1
     - ptu1_joint_2
     - ptu2_joint_1
     - ptu2_joint_2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ptu1_joint_1: {trajectory: 0.1, goal: 0.1}
      ptu1_joint_2: {trajectory: 0.1, goal: 0.1}
      ptu2_joint_1: {trajectory: 0.1, goal: 0.1}
      ptu2_joint_2: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10




